mode: daemonset
presets:
  logsCollection:
    enabled: true
  hostMetrics:
    enabled: true
  kubeletMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true

image:
  repository: docker.elastic.co/beats/elastic-agent
  tag: 8.15.0-SNAPSHOT
command:
  name: "/usr/share/elastic-agent/elastic-agent"
  extraArgs: ["otel", "-c", "/etc/elastic-agent/otel.yaml"]
livenessProbe:
  httpGet:
    port: 8888
    path: metrics
readinessProbe:
  httpGet:
    port: 8888
    path: metrics

securityContext:
  runAsUser: 0
  runAsGroup: 0

extraEnvs:
  - name: ELASTIC_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: elastic-secret-ds
        key: elastic_endpoint
  - name: ELASTIC_API_KEY
    valueFrom:
      secretKeyRef:
        name: elastic-secret-ds
        key: elastic_api_key
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

configMap:
  create: false
  existingName: elastic-otelcol-agent-ds
