default:
  image:
    repository: ghcr.io/elastic/opentelemetry-demo
    tag: 1.11.3

opentelemetry-collector:
  image:
    repository: docker.elastic.co/beats/elastic-agent
    tag: 8.16.0-SNAPSHOT
  mode: "deployment"
  presets:
    kubernetesAttributes:
      enabled: true
    kubernetesEvents:
      enabled: true
    clusterMetrics:
      enabled: true

  extraEnvs:
    - name: ELASTIC_AGENT_OTEL
      value: "true"
    - name: ELASTIC_APM_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: elastic-secret
          key: elastic_apm_endpoint
    - name: ELASTIC_APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: elastic-secret
          key: elastic_apm_secret_token

  config:
    receivers:
      redis: null
    exporters:
      otlphttp/prometheus: null
      opensearch: null
      otlp: null
      otlp/elastic:
        endpoint: ${env:ELASTIC_APM_ENDPOINT}
        compression: none
        headers:
          Authorization: Bearer ${env:ELASTIC_APM_SECRET_TOKEN}
    processors:
      k8sattributes:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
          - container.image.name
          - container.image.tag
          - k8s.container.name
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      resource:
        attributes:
        - key: service.instance.id
          from_attribute: k8s.pod.uid
          action: insert
        - key: deployment.environment
          value: "opentelemetry-demo"
          action: upsert

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes, memory_limiter, transform, resource, batch]
          exporters: [otlp/elastic, spanmetrics]
        metrics:
          receivers: [httpcheck/frontendproxy, otlp, spanmetrics]
          processors: [k8sattributes, memory_limiter, resource, batch]
          exporters: [otlp/elastic]
        logs:
          processors: [k8sattributes, memory_limiter, resource, batch]
          exporters: [otlp/elastic]


opensearch:
  enabled: false

grafana:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false
