components:
  frontendProxy:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: otel-demo.104.197.4.188.nip.io
          paths:
            - path: /
              pathType: Prefix
              port: 8080
  adService:
    envOverrides:
      - name: OTEL_SDK_DISABLED
        value: 'true'
