default:
  image:
    repository: ghcr.io/elastic/opentelemetry-demo
    tag: 1.10.1

opentelemetry-collector:
  image:
    repository: docker.elastic.co/beats/elastic-agent
    tag: 8.15.0-SNAPSHOT
  command:
    name: "/usr/share/elastic-agent/elastic-agent"
    extraArgs: ["otel", "-c", "/etc/elastic-agent/otel.yaml"]
  mode: "deployment"
  presets:
    kubernetesAttributes:
      enabled: true
    kubernetesEvents:
      enabled: true
    clusterMetrics:
      enabled: true

  extraEnvs:
    - name: ELASTIC_APM_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: elastic-secret
          key: elastic_apm_endpoint
    - name: ELASTIC_APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: elastic-secret
          key: elastic_apm_secret_token

  configMap:
    create: false
    existingName: elastic-otelcol-agent

  livenessProbe:
    httpGet:
      port: 8888
      path: metrics
  readinessProbe:
    httpGet:
      port: 8888
      path: metrics

opensearch:
  enabled: false

grafana:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false
