default:
  image:
    repository: ghcr.io/elastic/opentelemetry-demo
    tag: 1.10.1

opentelemetry-collector:
  image:
    repository: docker.elastic.co/beats/elastic-agent
    tag: 8.15.0-SNAPSHOT
  command:
    name: "/usr/share/elastic-agent/elastic-agent"
    extraArgs: ["otel", "-c", "/etc/elastic-agent/otel.yaml"]
  mode: "deployment"
  presets:
    kubernetesAttributes:
      enabled: true
    kubernetesEvents:
      enabled: true
    clusterMetrics:
      enabled: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0

  extraEnvs:
    - name: ELASTIC_APM_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: elastic-secret
          key: elastic_apm_endpoint
    - name: ELASTIC_APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: elastic-secret
          key: elastic_apm_secret_token
  extraVolumeMounts:
    - name: varlogpods
      mountPath: /var/log/pods
      readOnly: true
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
    - name: hostfs
      mountPath: /hostfs
      readOnly: true
      mountPropagation: HostToContainer
  extraVolumes:
    - name: varlogpods
      hostPath:
        path: /var/log/pods
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    - name: hostfs
      hostPath:
        path: /

  configMap:
    create: false
    existingName: elastic-otelcol-agent

  livenessProbe:
    httpGet:
      port: 8888
      path: metrics
  readinessProbe:
    httpGet:
      port: 8888
      path: metrics

opensearch:
  enabled: false

grafana:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false
