receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  debug:

processors:
  batch:
  # Transforming span names for easier identification. See: https://github.com/open-telemetry/opentelemetry-demo/issues/1676
  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        conditions:
          - IsString(attributes["http.url"])
        statements:
          - merge_maps(attributes, URL(attributes["http.url"]), "upsert")
          # This pattern should correctly capture the first one or two segments of a URL and assign them to the short_url named group.
          - merge_maps(attributes, ExtractPatterns(attributes["url.path"], "^(?P<short_url>\\/[^\\/]+(\\/[^\\/]+)?)"), "upsert")
          - set(name, attributes["short_url"])
  resource:
    attributes:
      - key: deployment.environment
        value: "opentelemetry-demo"
        action: upsert

connectors:
  spanmetrics:
