receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  debug:

processors:
  batch:
  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        conditions:
          - IsString(attributes["http.url"])
        statements:
          - merge_maps(attributes, URL(attributes["http.url"]), "upsert")
          - set(name, attributes["url.path"])
  resource:
    attributes:
      - key: deployment.environment
        value: "opentelemetry-demo"
        action: upsert

connectors:
  spanmetrics:
