#!/bin/bash

# Define bash colors
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

die () {
  echo -e "${BRed}ERROR: $1${Color_Off}"
  exit 1
}

if [ -z "${KIBANA_URL}" ]; then
  die "You must set KIBANA_URL to a valid Kibana URL"
fi

if [ -z "${KIBANA_USER}" ]; then
  die "You must set KIBANA_USER to a valid admin Kibana user"
fi

if [ -z "${KIBANA_PASSWORD}" ]; then
  die "You must set KIBANA_PASSWORD for the specified user"
fi

if [[ "$1" != -* ]]; then
    action="$1"
    shift
fi

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -s) service_name="$2"; shift ;;
    esac
    shift
done

if [[ -z "$service_name" ]]; then
  die "You must specify service name using -s option"
fi

release_timestamp=$(date -u -v-5M +"%Y-%m-%dT%H:%M:%SZ")
new_service_version="2.0.0"

old_service_version="1.0.0"
rollback_timestamp=$(date -u -v-1M +"%Y-%m-%dT%H:%M:%SZ")

ANNOTATION_API_ENDPOINT="$KIBANA_URL/api/apm/services/$service_name/annotation"

service_version=$( [[ "$action" == "restore" ]] && echo "$old_service_version" || echo "$new_service_version" )
message=$( [[ "$action" == "restore" ]] && echo "Version rollback" || echo "New version release" )
timestamp=$( [[ "$action" == "restore" ]] && echo "$rollback_timestamp" || echo "$release_timestamp" )

REQUEST_BODY=$(cat <<EOF
{
    "@timestamp": "$timestamp",
    "service": {
        "version": "$service_version"
    },
    "message": "$message for $service_name: $service_version"
}
EOF
)

HEADERS=(
    -H "kbn-xsrf: true" \
    -H "elastic-api-version: 2023-10-31" \
    -H "Content-Type: application/json"
)

response=$(curl -s -X POST -u "$KIBANA_USER:$KIBANA_PASSWORD" "${HEADERS[@]}" -d "$REQUEST_BODY" "$ANNOTATION_API_ENDPOINT")

statusCode=$(echo "$response" | jq -r '.statusCode')
ok=$(echo "$response" | jq -r '.ok')

if [[ "$statusCode" != null && "$statusCode" != 200 ]]; then
    die "Creating annotation failed: $response"
fi

if [[ "$ok" != null && "$ok" == false ]]; then
    die "Creating annotation failed: $response"
fi

echo "$message for $service_name: $service_version"
